### ISSUE TITLE
\angular8-example-app-master\node_modules\.staging\@angular\core-9df594b5\fesm5\core.js.map

### ISSUE THREAD

**Issue by snagelli** [Ismaestro/angular8-example-app#47]
npm ERR! path F:\angular8-example-app-master\node_modules\.staging\@angular\core-9df594b5\fesm5\core.js.map
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'F:\angular8-example-app-master\node_modules\.staging\@angular\core-9df594b5\fesm5\core.js.map'
npm ERR!  [OperationalError: EPERM: operation not permitted, unlink 'F:\angular8-example-app-master\node_modules\.staging\@angular\core-9df594b5\fesm5\core.js.map'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, unlink 'F:\angular8-example-app-master\node_modules\.staging\@angular\core-9df594b5\fesm5\core.js.map'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'unlink',
npm ERR!     path: 'F:\\angular8-example-app-master\\node_modules\\.staging\\@angular\\core-9df594b5\\fesm5\\core.js.map'
npm ERR!   },
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink ' +
npm ERR!     "'F:\\angular8-example-app-master\\node_modules\\.staging\\@angular\\core-9df594b5\\fesm5\\core.js.map'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'F:\\angular8-example-app-master\\node_modules\\.staging\\@angular\\core-9df594b5\\fesm5\\core.js.map',
npm ERR!   parent: 'angular8-example-app-master'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

**Comment by snagelli** [comment]
Could you please help me on this issue

**Comment by Ismaestro** [comment]
What command did you run? I need a minimum info and context, not only the error... It seems to be a permissions issue. Try run the command with sudo, or give the right access to that user in that folder...

**Comment by Ismaestro** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
